### Endpoint to get all permissions. Require authorization

GET http://localhost:3001/permission
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhYmFzZSI6ImFlbGVtIiwiX2lkIjoiNjFkZWRlMWNhMDBhMTY0NjRiODZkYTFiIiwiaWF0IjoxNjQyMzY2OTU2LCJleHAiOjE2NDI3MjY5NTZ9.hRBznCiVm4QO2SX0cwOn5GNksUJot4HbSgssfTst-L0


###endpoint to get all permissions by an user. Requires authorization

GET http://localhost:3001/permission/byUser/615b18891327a6f9eb5b7e0d
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhYmFzZSI6ImFlbGVtIiwiX2lkIjoiNjFkZWRlMWNhMDBhMTY0NjRiODZkYTFiIiwiaWF0IjoxNjQyMzY2OTU2LCJleHAiOjE2NDI3MjY5NTZ9.hRBznCiVm4QO2SX0cwOn5GNksUJot4HbSgssfTst-L0
