###endpoint to login user http://localhost:{port}/auth/login/{dbname}

POST http://localhost:3001/auth/login/visualizar HTTP/1.1
Content-Type: 'application/json'

{
    "email": "matias1.santillan@gmail.com",
    "password": "P0r0ng4_"
}


### endpoint to validate expiration of jwt http://localhost:{port}/auth/validate/{dbname}

POST http://localhost:3001/auth/validate HTTP/1.1
Content-Type: 'application/json'
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhYmFzZSI6InZpc3VhbGl6YXIiLCJfaWQiOiI2MTdiNGVlNWRmNDQ2Y2ZiNjM3ZWNmZDQiLCJpYXQiOjE2NDIyMTE2MzUsImV4cCI6MTY0MjU3MTYzNX0.5iyB-XnMUPBSEYud7rTzBseZ63hm-w9kbXHBHcsomS4 

